### ISSUE TITLE
build still includes pre/post trans scriptlet despite #254

### ISSUE THREAD

**Issue by ScrumpyJack** [nebula-plugins/gradle-ospackage-plugin#285]
❯ gradle --version
Gradle 4.6
Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Mac OS X 10.12.6 x86_64

❯ grep classpath build.gradle
            classpath 'com.netflix.nebula:gradle-ospackage-plugin:4.8.0'

I have not declared any scripts in build.gradle, yet, when the plugin builds a package, i get:

rpm -qp --scripts build/distributions/mypackage.version.noarch.rpm

pretrans scriptlet (using /bin/sh):
posttrans scriptlet (using /bin/sh):

This breaks any anaconda kickstart install where no /bin/sh is available.

Shouldn't this have been fixed by https://github.com/nebula-plugins/gradle-ospackage-plugin/pull/254 ?

**Comment by malejpavouk** [comment]
Strange, we are using also 4.8.0 and we had the exactly same problem with 4.4.0 and the issue is fixed for us now.

**Comment by StefanZi** [comment]
I can confirm this problem still exists on a freshly installed CentOS 7 x64 (1804) VM:

```
# gradle -v

------------------------------------------------------------
Gradle 4.8
------------------------------------------------------------

Build time:   2018-06-04 10:39:58 UTC
Revision:     9e1261240e412cbf61a5e3a5ab734f232b2f887d

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_171 (Oracle Corporation 25.171-b10)
OS:           Linux 3.10.0-862.el7.x86_64 amd64
```

My minimal build.gradle:
```
plugins {
  id "nebula.rpm" version "4.8.0"
}

task buildRpm (type: Rpm) {
}
```

Running `gradle buildRpm` creates a RPM at build/distributions:

```
# rpm -qp --scripts gradlerpmtest-unspecified.noarch.rpm
pretrans scriptlet (using /bin/sh):

posttrans scriptlet (using /bin/sh):
 RPM_ARCH=noarch
 RPM_OS=unknown
 RPM_PACKAGE_NAME=gradlerpmtest
 RPM_PACKAGE_VERSION=unspecified
 RPM_PACKAGE_RELEASE=
```

From what I've seen `/bin/sh` is the default interpreter in the redline library (`1.2.6` in my case), but the pre and post-trans sections shouldn't be in the file anyway (and the redline's methods for creating these sections are not called because of the changes in #254 )

**Comment by rpalcolea** [comment]
This is fixed in v5.0.4
